title: Aidan's Blog
email: aidan79225@gmail.com
description: >-
  This is my blog.
baseurl: ""
url: "https://aidan79225.github.io"
github_username:  aidan79225
repository: "Aidan79225/aidan79225.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"
name: Aidan Wang

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      author: Aidan Wang
      show_date: true
      comments: true

enable_copy_code_button: true

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Aidan79225"
  content: "© 2025 Aidan's Blog"
collections:
  - staff_members

categories:
  - tech
  - food

include: ["_pages"]
mathjax: true
mathjax_options:
  tex:
    inlineMath: [["$", "$"]]
    displayMath: [["$$", "$$"]]
  
comments:
  provider: "utterances"
  utterances:
    theme: "dark-blue"
    issue_term: "pathname"
    label: "comment"