title: Aidan's Blog
email: aidan79225@gmail.com
description: >-
  This is my blog.
baseurl: ""
url: ""
github_username:  aidan79225

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "dark"
name: Aidan Wang

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

author:
  name: "Aidan Wang"
  avatar: "/assets/images/avatar.webp"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Taiwan"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aidan79225"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/aidan79225/"
