title: Aidan's Blog
email: aidan79225@gmail.com
description: >-
  This is my blog.
baseurl: ""
url: ""
github_username:  aidan79225

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
name: Aidan Wang

plugins:
  - jekyll-feed

