// Generate dist/sw.js after `astro build`: a service worker that precaches the
// whole site (minus OG images) so the blog is fully readable offline after one
// visit. Runs as part of `npm run build`; dist/ is not committed, so the
// worker is regenerated — with a fresh content-hash version — on every build.
//
// Update model: any content change → different VERSION → browsers reinstall
// the worker, precache the new snapshot into a new cache, and drop the old one
// on activate. skipWaiting/clients.claim make the swap take effect promptly.
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { shouldPrecache, toUrl } from '../src/lib/sw-manifest.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

try {
  await stat(DIST);
} catch {
  console.error('gen-sw: dist/ not found — run `astro build` first.');
  process.exit(1);
}

const files = (await walk(DIST))
  .map((f) => relative(DIST, f))
  .filter(shouldPrecache)
  .sort();

// Bump when the worker template below changes behaviour, so clients rotate
// to a fresh cache even if site content is identical.
const SW_REVISION = 'v4';

// Version = hash of every precached file's content, so identical rebuilds
// produce an identical worker (no pointless client re-downloads).
const h = createHash('sha256');
h.update(SW_REVISION);
let bytes = 0;
for (const f of files) {
  const buf = await readFile(join(DIST, f));
  bytes += buf.length;
  h.update(f).update('\0').update(buf);
}
const version = h.digest('hex').slice(0, 12);
const urls = files.map(toUrl);

const sw = `/* generated by scripts/gen-sw.mjs — do not edit */
const VERSION = '${version}';
const CACHE = 'site-' + VERSION;
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    // Not cache.addAll: that rejects the whole install if ANY response is
    // non-ok, and GitHub Pages serves /404.html with status 404 — which would
    // brick every install. Instead fetch individually so /404.html can be
    // cached regardless of status. But the install is still all-or-nothing:
    // if anything else fails (e.g. the network drops mid-install) we THROW so
    // the install fails and the browser retries on the next page load —
    // activating with a partial cache would serve 404s offline until the next
    // deploy. Entries cached by an earlier failed attempt of this same
    // VERSION are skipped, so retries resume instead of starting over.
    const c = await caches.open(CACHE);
    const CONCURRENCY = 8;
    const TOTAL = PRECACHE.length;
    let done = 0;
    // Progress for the page's unobtrusive indicator (see BaseLayout). The
    // installing worker doesn't control any page yet → includeUncontrolled.
    async function report(final) {
      try {
        const cs = await self.clients.matchAll({ includeUncontrolled: true });
        for (const cl of cs) cl.postMessage({ type: 'sw-precache', done: final ? TOTAL : done, total: TOTAL });
      } catch {}
    }
    async function fill(track) {
      const failed = [];
      let i = 0;
      async function worker() {
        while (i < PRECACHE.length) {
          const url = PRECACHE[i++];
          if (await c.match(url)) {
            if (track && ++done % 16 === 0) report();
            continue;
          }
          try {
            const res = await fetch(new Request(url, { cache: 'reload' }));
            if (res.ok || url === '/404.html') {
              await c.put(url, res);
              if (track && ++done % 16 === 0) report();
            } else failed.push(url);
          } catch {
            failed.push(url);
          }
        }
      }
      await Promise.all(Array.from({ length: CONCURRENCY }, worker));
      return failed;
    }
    let failed = await fill(true);
    if (failed.length) failed = await fill(false); // retry round: small, no progress churn
    if (failed.length) throw new Error('precache incomplete: ' + failed.length + ' failed');
    await report(true); // 100% → page shows "done" state, then fades it out
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

async function offlineFallback(url) {
  const c = await caches.open(CACHE);
  return (
    (await c.match(url.pathname)) ||
    (await c.match(url.pathname.endsWith('/') ? url.pathname.slice(0, -1) : url.pathname + '/')) ||
    (await c.match('/404.html')) ||
    (await c.match('/'))
  );
}

// Pages: network-first (always fresh when online), full cache fallback offline.
async function handleNav(req, url) {
  let fresh;
  try {
    fresh = await fetch(req);
  } catch {
    const hit = await offlineFallback(url);
    if (hit) return hit;
    throw new Error('offline, uncached');
  }
  if (fresh.ok) {
    try { (await caches.open(CACHE)).put(url.pathname, fresh.clone()); } catch {}
  }
  return fresh;
}

// Assets (hashed _astro/, icons, JSON indexes): cache-first — a new deploy
// ships a new VERSION and re-precaches, so staleness is bounded by deploys.
async function handleAsset(req) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const fresh = await fetch(req); // may throw offline → outer fallback
  if (fresh.ok) {
    try { (await caches.open(CACHE)).put(req, fresh.clone()); } catch {}
  }
  return fresh;
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // utterances / analytics: pass through
  if (url.pathname.startsWith('/og/')) return;     // share images: network only

  // Fail-open: any unexpected error inside our handlers falls back to a plain
  // network fetch — the worker must never be the reason a click goes nowhere.
  if (req.mode === 'navigate') {
    e.respondWith(handleNav(req, url).catch(() => fetch(req)));
    return;
  }
  e.respondWith(handleAsset(req).catch(() => fetch(req)));
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(
  `gen-sw: ${urls.length} URLs precached (${(bytes / 1024 / 1024).toFixed(1)} MB), version ${version}`
);
