// Generate dist/sw.js after `astro build`: a service worker that precaches the
// whole site (minus OG images) so the blog is fully readable offline after one
// visit. Runs as part of `npm run build`; dist/ is not committed, so the
// worker is regenerated — with a fresh content-hash version — on every build.
//
// Update model: any content change → different VERSION → browsers reinstall
// the worker, precache the new snapshot into a new cache, and drop the old one
// on activate. skipWaiting/clients.claim make the swap take effect promptly.
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { shouldPrecache, toUrl } from '../src/lib/sw-manifest.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

try {
  await stat(DIST);
} catch {
  console.error('gen-sw: dist/ not found — run `astro build` first.');
  process.exit(1);
}

const files = (await walk(DIST))
  .map((f) => relative(DIST, f))
  .filter(shouldPrecache)
  .sort();

// Version = hash of every precached file's content, so identical rebuilds
// produce an identical worker (no pointless client re-downloads).
const h = createHash('sha256');
let bytes = 0;
for (const f of files) {
  const buf = await readFile(join(DIST, f));
  bytes += buf.length;
  h.update(f).update('\0').update(buf);
}
const version = h.digest('hex').slice(0, 12);
const urls = files.map(toUrl);

const sw = `/* generated by scripts/gen-sw.mjs — do not edit */
const VERSION = '${version}';
const CACHE = 'site-' + VERSION;
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    const CHUNK = 20; // small batches: one flaky fetch only fails its chunk retry, not the lot
    for (let i = 0; i < PRECACHE.length; i += CHUNK) {
      const part = PRECACHE.slice(i, i + CHUNK).map((u) => new Request(u, { cache: 'reload' }));
      try {
        await c.addAll(part);
      } catch {
        await c.addAll(part); // one retry per chunk, then give up loudly
      }
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

async function offlineFallback(url) {
  const c = await caches.open(CACHE);
  return (
    (await c.match(url.pathname)) ||
    (await c.match(url.pathname.endsWith('/') ? url.pathname.slice(0, -1) : url.pathname + '/')) ||
    (await c.match('/404.html')) ||
    (await c.match('/'))
  );
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // utterances / analytics: pass through
  if (url.pathname.startsWith('/og/')) return;     // share images: network only

  // Pages: network-first (always fresh when online), full cache fallback offline.
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        if (fresh.ok) {
          try { (await caches.open(CACHE)).put(url.pathname, fresh.clone()); } catch {}
        }
        return fresh;
      } catch {
        return (await offlineFallback(url)) || Response.error();
      }
    })());
    return;
  }

  // Assets (hashed _astro/, icons, JSON indexes): cache-first — a new deploy
  // ships a new VERSION and re-precaches, so staleness is bounded by deploys.
  e.respondWith((async () => {
    const hit = await caches.match(req);
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh.ok) {
        try { (await caches.open(CACHE)).put(req, fresh.clone()); } catch {}
      }
      return fresh;
    } catch {
      return (await caches.match(req, { ignoreSearch: true })) || Response.error();
    }
  })());
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(
  `gen-sw: ${urls.length} URLs precached (${(bytes / 1024 / 1024).toFixed(1)} MB), version ${version}`
);
